name: igor.localization
description: A simple localization library with support for adaptive texts
version: 1.0.0
repository: https://github.com/Michal-MK/Localization

environment:
  sdk: ^3.0.3

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0